#! /bin/bash
for (( i=0 ; i<=10 ; i++ ))
do
echo "enter the value"
read value 
case ${value::1} in 
   [a-z])
   echo "you entered a string";;
   ["-a"-"-z"][a-z])
   echo "you entered a string";;
   [0-9])
   echo "you entered a number";;
   ["-1"-"-10"])
   echo "you entered a number";;
esac
done
