#! /bin/bash
function power(){
local n=$1
for (( i=1 ; i<=n ; i++ ));
do
t=0
result=$((2**i))
if [ $n -eq $result ]
then
t=1 
echo "the number is power of two "
echo "the number is power of two in $i of two "
break;
#fi
#exit 0
elif [ $n -ne $result ]
then
t=2
fi
done
if [ $t -eq 2 ]
then
echo "the number is not power of two"
fi
}
for (( j=0 ; j<=10 ; j++ ))
do 
echo "enter number"
read num
power $num
done
